# Generated by Django 4.2.2 on 2023-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('img1', models.ImageField(upload_to='pic')),
                ('desc1', models.TextField()),
            ],
        ),
    ]
