# Generated by Django 4.2.2 on 2023-06-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='img1',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
